database: &DATABASE
  adapter: mysql2
  encoding: utf8
  host: localhost
  pool: 25
  timeout: 5000

development:
  <<: *DATABASE
  database: fb_event_development
  username: root
  password: root

production:
  adapter: postgresql
  host: ec2-107-21-126-45.compute-1.amazonaws.com
  database: d8qaub5ibrvf80
  pool: 5
  timeout: 5000
  username: yavuhdjrtkjufq
  password: ibLbquqgV3pTQoKsE1i5oSxzl8

staging:
  adapter: postgresql
  encoding: unicode
  database: db/recommend_staging
  pool: 5
  username: ptsimbxenr
  password: -sAcp6PYnGfKndlFNLbr

test:
  <<: *DATABASE
  database: recommend_test
  username: root
  password: root
